### ISSUE TITLE
Visia theme ?doesn't work at all 

### ISSUE THREAD

**Issue by chartivson** [terriann/Simply-Pinterest-WordPress-Plugin#30] opened 2015-09-19 06:41 UTC
Hi - i use the visia theme for a clients website and your plug-in seems absolutely un effective. it simply doesn't show up and the only thing i can think of is that perhaps there is 2 J.s query running but there wasn't any complications so what do you think i should do ? Thanks

**Comment by terriann** [comment] 2015-09-19 15:40
That's quite a harsh way to report a bug but here's my response:

My free software cannot support every theme that exists.  It's designed to work on the most common standard "blogging" cases and even then it's designed to apply to images added **inside** the body of the post not featured images or other images integrated through the theme.

You didn't provide a URL for me to look at and I don't own this theme so unless you can provide additional detail I'll be closing this ticket.

**Closed by terriann** 2015-09-19 15:40 UTC

**Comment by chartivson** [comment] 2015-09-19 15:51
Teri-
i apologize about being harsh. You are correct. I should have been empathic. You did do the work of creating a free app. again I’m sorry.
The url is www.azpinnacleturf.com <http://www.azpinnacleturf.com/>  .  If you can help me solve this I can surely spend an equal amount of time with praise and review.
I appreciate the dedication it takes to work out kinks and issues. I’m not a pro and my support ticket reflected worse on me than you.
sorry again. Cheers - Dean 


dean charter
lubriceuticals@gmail.com <mailto:lubriceuticlas@gmail.com>
9492575071

**Comment by terriann** [comment] 2015-09-19 18:34
Thanks Dean

The plugin is actually working perfectly as it was designed on your blog page: https://azpinnacleturf.com/the-blog/ as well as on some of the segments on the "single page" style home page: https://azpinnacleturf.com/#our-work-2

I don't know what specifically you expect that the plugin isn't doing.  It wasn't designed with "WordPress as a CMS" style sites in mind.The single page layouts where the pages are structured so differently than the themes I intended to support (namely the default WordPress themes, Genesis and Thesis) which all have a very predictable blogging layout so I don't know how I can help here.

![screenshot 1](https://cloud.githubusercontent.com/assets/316632/9977575/14d6f77e-5edb-11e5-8f0e-82fb3380b3dc.png)
![screenshot](https://cloud.githubusercontent.com/assets/316632/9977576/14d75020-5edb-11e5-97c1-28a17b9ddda3.png)

**Comment by chartivson** [comment] 2015-09-19 19:53
Okay - i feel really silly. however, i am happy that they are working. I will spread the good news immediately. I suppose in my frustration with this last hurdle, i hadn’t scrolled enough. Do you have any advice for the sliders and galleries ? If you do let me know. Thanks for showing me better manners on forums — i’ll be handling myself better.    This is a random question. What is your IQ?    As you can tell I am not talented developer or web person. This way my first site I ever built. I am used to being able to solve and resolve matters on my way. i am an entrepreneur and I have a vision for a very specific type of service which requires an IQ over 107? if you know your IQ let me know and I will share this next idea and you can feedback as your opinion matters to me. Thanks - I appreciate you. Dean                                  



 Thanks - Dean 
dean charter
lubriceuticals@gmail.com <mailto:lubriceuticlas@gmail.com>
9492575071

**Comment by chartivson** [comment] 2015-09-19 19:57
Didn't realize my email was going straight onto GITHUB but this plug-in worked very well and any doubt that it didn't was my own fault. Quick response and quite professionally. It was actually 1 2 3 to install as well. Thanks again.
